apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ola-monitoring
data:
  NEXT_PUBLIC_API_URL: ""
  INTERNAL_API_URL: "http://backend-svc:3000"
  PORT: "3001"
  HOSTNAME: "0.0.0.0"
