apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: ola-monitoring
spec:
  type: NodePort
  selector:
    app: ola-frontend
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
